# Examples and Exercises from Think Stats, 2nd Edition

http://thinkstats2.com

Copyright 2016 Allen B. Downey

MIT License: https://opensource.org/licenses/MIT


In [3]:
from __future__ import print_function, division

import nsfg

## Examples from Chapter 1

Read NSFG data into a Pandas DataFrame.

In [4]:
preg = nsfg.ReadFemPreg()
preg.head()

caseid  pregordr  howpreg_n  howpreg_p  moscurrp  nowprgdk  pregend1  \
0       1         1        NaN        NaN       NaN       NaN       6.0   
1       1         2        NaN        NaN       NaN       NaN       6.0   
2       2         1        NaN        NaN       NaN       NaN       5.0   
3       2         2        NaN        NaN       NaN       NaN       6.0   
4       2         3        NaN        NaN       NaN       NaN       6.0   

   pregend2  nbrnaliv  multbrth     ...       laborfor_i  religion_i  metro_i  \
0       NaN       1.0       NaN     ...                0           0        0   
1       NaN       1.0       NaN     ...                0           0        0   
2       NaN       3.0       5.0     ...                0           0        0   
3       NaN       1.0       NaN     ...                0           0        0   
4       NaN       1.0       NaN     ...                0           0        0   

       basewgt  adj_mod_basewgt      finalwgt  secu_p  sest  cmintvw  \
0  3410.389399      3869.349602   6448.271112       2     9      NaN   
1  3410.389399      3869.349602   6448.271112       2     9      NaN   
2  7226.301740      8567.549110  12999.542264       2    12      NaN   
3  7226.301740      8567.549110  12999.542264       2    12      NaN   
4  7226.301740      8567.549110  12999.542264       2    12      NaN   

   totalwgt_lb  
0       8.8125  
1       7.8750  
2       9.1250  
3       7.0000  
4       6.1875  

[5 rows x 244 columns]

In [5]:
preg

caseid  pregordr  howpreg_n  howpreg_p  moscurrp  nowprgdk  pregend1  \
0           1         1        NaN        NaN       NaN       NaN       6.0   
1           1         2        NaN        NaN       NaN       NaN       6.0   
2           2         1        NaN        NaN       NaN       NaN       5.0   
3           2         2        NaN        NaN       NaN       NaN       6.0   
4           2         3        NaN        NaN       NaN       NaN       6.0   
5           6         1        NaN        NaN       NaN       NaN       6.0   
6           6         2        NaN        NaN       NaN       NaN       6.0   
7           6         3        NaN        NaN       NaN       NaN       6.0   
8           7         1        NaN        NaN       NaN       NaN       5.0   
9           7         2        NaN        NaN       NaN       NaN       5.0   
10         12         1        NaN        NaN       NaN       NaN       5.0   
11         14         1        NaN        NaN       NaN       NaN       6.0   
12         14         2        NaN        NaN       NaN       NaN       6.0   
13         14         3        NaN        NaN       NaN       NaN       3.0   
14         15         1        NaN        NaN       NaN       NaN       1.0   
15         15         2        NaN        NaN       NaN       NaN       6.0   
16         15         3        NaN        NaN       NaN       NaN       6.0   
17         18         1        NaN        NaN       NaN       NaN       5.0   
18         18         2        NaN        NaN       NaN       NaN       1.0   
19         21         1        NaN        NaN       NaN       NaN       6.0   
20         21         2        NaN        NaN       NaN       NaN       6.0   
21         23         1        NaN        NaN       NaN       NaN       6.0   
22         23         2        NaN        NaN       NaN       NaN       1.0   
23         24         1        NaN        NaN       NaN       NaN       6.0   
24         24         2        NaN        NaN       NaN       NaN       6.0   
25         24         3        NaN        NaN       NaN       NaN       6.0   
26         28         1        NaN        NaN       NaN       NaN       6.0   
27         31         1        NaN        NaN       NaN       NaN       6.0   
28         31         2        NaN        NaN       NaN       NaN       6.0   
29         31         3        NaN        NaN       NaN       NaN       6.0   
...       ...       ...        ...        ...       ...       ...       ...   
13563   12547         2        NaN        NaN       NaN       NaN       6.0   
13564   12547         3        NaN        NaN       NaN       NaN       6.0   
13565   12550         1        NaN        NaN       NaN       NaN       6.0   
13566   12551         1        NaN        NaN       NaN       NaN       5.0   
13567   12554         1        NaN        NaN       NaN       NaN       3.0   
13568   12554         2        NaN        NaN       NaN       NaN       4.0   
13569   12556         1        NaN        NaN       NaN       NaN       6.0   
13570   12556         2        NaN        NaN       NaN       NaN       6.0   
13571   12556         3        NaN        NaN       NaN       NaN       6.0   
13572   12556         4        NaN        NaN       NaN       NaN       6.0   
13573   12561         1        NaN        NaN       NaN       NaN       6.0   
13574   12561         2        NaN        NaN       NaN       NaN       6.0   
13575   12564         1        NaN        NaN       NaN       NaN       3.0   
13576   12565         1        NaN        NaN       NaN       NaN       6.0   
13577   12565         2       35.0        1.0       8.0       NaN       NaN   
13578   12566         1        NaN        NaN       NaN       NaN       6.0   
13579   12566         2        NaN        NaN       NaN       NaN       6.0   
13580   12568         1        NaN        NaN       NaN       NaN       1.0   
13581   12568         2        NaN        NaN       NaN  

Print the column names.

In [6]:
preg.columns

Index(['caseid', 'pregordr', 'howpreg_n', 'howpreg_p', 'moscurrp', 'nowprgdk',
       'pregend1', 'pregend2', 'nbrnaliv', 'multbrth',
       ...
       'laborfor_i', 'religion_i', 'metro_i', 'basewgt', 'adj_mod_basewgt',
       'finalwgt', 'secu_p', 'sest', 'cmintvw', 'totalwgt_lb'],
      dtype='object', length=244)

Select a single column name.

In [7]:
preg.columns[1]

'pregordr'

Select a column and check what type it is.

In [9]:
pregordr = preg['pregordr']
type(pregordr)

pandas.core.series.Series

Print a column.

In [10]:
pregordr

0        1
1        2
2        1
3        2
4        3
5        1
6        2
7        3
8        1
9        2
10       1
11       1
12       2
13       3
14       1
15       2
16       3
17       1
18       2
19       1
20       2
21       1
22       2
23       1
24       2
25       3
26       1
27       1
28       2
29       3
        ..
13563    2
13564    3
13565    1
13566    1
13567    1
13568    2
13569    1
13570    2
13571    3
13572    4
13573    1
13574    2
13575    1
13576    1
13577    2
13578    1
13579    2
13580    1
13581    2
13582    3
13583    1
13584    2
13585    1
13586    2
13587    3
13588    1
13589    2
13590    3
13591    4
13592    5
Name: pregordr, dtype: int64

Select a single element from a column.

In [7]:
pregordr[0]

1

Select a slice from a column.

In [11]:
pregordr[2:6]

2    1
3    2
4    3
5    1
Name: pregordr, dtype: int64

Select a column using dot notation.

In [13]:
pregordr = preg.pregordr

Count the number of times each value occurs.

In [18]:
preg.outcome.value_counts(sort=False)

1    9148
2    1862
3     120
4    1921
5     190
6     352
Name: outcome, dtype: int64

Check the values of another variable.

In [17]:
preg.birthwgt_lb.value_counts().sort_index()

0.0        8
1.0       40
2.0       53
3.0       98
4.0      229
5.0      697
6.0     2223
7.0     3049
8.0     1889
9.0      623
10.0     132
11.0      26
12.0      10
13.0       3
14.0       3
15.0       1
Name: birthwgt_lb, dtype: int64

Make a dictionary that maps from each respondent's `caseid` to a list of indices into the pregnancy `DataFrame`.  Use it to select the pregnancy outcomes for a single respondent.

In [21]:
caseid = 10229
preg_map = nsfg.MakePregMap(preg)
indices = preg_map[caseid]
preg_map

defaultdict(list,
            {1: [0, 1],
             2: [2, 3, 4],
             6: [5, 6, 7],
             7: [8, 9],
             12: [10],
             14: [11, 12, 13],
             15: [14, 15, 16],
             18: [17, 18],
             21: [19, 20],
             23: [21, 22],
             24: [23, 24, 25],
             28: [26],
             31: [27, 28, 29],
             36: [30, 31],
             38: [32, 33, 34],
             39: [35, 36],
             44: [37, 38, 39, 40],
             45: [41],
             46: [42, 43],
             49: [44, 45, 46, 47],
             51: [48, 49, 50],
             52: [51],
             57: [52, 53, 54],
             60: [55, 56],
             63: [57, 58, 59],
             69: [60],
             70: [61, 62, 63, 64],
             71: [65],
             72: [66, 67],
             73: [68, 69],
             77: [70, 71],
             80: [72, 73, 74, 75, 76],
             81: [77],
             86: [78, 79, 80],
             90: [81, 82],

In [22]:
preg.outcome[indices].values

array([4, 4, 4, 4, 4, 4, 1])

## Exercises

Select the `birthord` column, print the value counts, and compare to results published in the [codebook](http://www.icpsr.umich.edu/nsfg6/Controller?displayPage=labelDetails&fileCode=PREG&section=A&subSec=8016&srtLabel=611933)

In [24]:
# Solution goes here
preg.birthord.value_counts()

1.0     4413
2.0     2874
3.0     1234
4.0      421
5.0      126
6.0       50
7.0       20
8.0        7
9.0        2
10.0       1
Name: birthord, dtype: int64

We can also use `isnull` to count the number of nans.

In [25]:
preg.birthord.isnull().sum()

4445

Select the `prglngth` column, print the value counts, and compare to results published in the [codebook](http://www.icpsr.umich.edu/nsfg6/Controller?displayPage=labelDetails&fileCode=PREG&section=A&subSec=8016&srtLabel=611931)

In [34]:
# Solution goes here
preglngth_order = preg['prglngth'].value_counts().sort_index()

In [39]:
preglngth = preg['prglngth']
print(sum(preglngth_order[0:14]))
print(sum(preglngth_order[15:27]))
print(sum(preglngth_order[28:51]))

3522
764
9270


To compute the mean of a column, you can invoke the `mean` method on a Series.  For example, here is the mean birthweight in pounds:

In [16]:
preg.totalwgt_lb.mean()

7.265628457623368

Create a new column named <tt>totalwgt_kg</tt> that contains birth weight in kilograms.  Compute its mean.  Remember that when you create a new column, you have to use dictionary syntax, not dot notation.

In [41]:
# Solution goes here
preg['totalwgt_kg'] = preg.totalwgt_lb * 0.453592
preg['totalwgt_kg']

0        3.997279
1        3.572037
2        4.139027
3        3.175144
4        2.806601
5        3.883881
6        4.337473
7        3.798833
8        3.430289
9        3.005047
10       3.543687
11       3.175144
12       1.814368
13            NaN
14            NaN
15       3.486988
16       3.401940
17       2.863300
18            NaN
19       3.968930
20       3.713785
21       2.523105
22            NaN
23       3.061746
24       3.345241
25       3.090095
26       3.685435
27       3.231843
28       2.749901
29       3.373591
           ...   
13563    3.486988
13564    3.458639
13565    3.685435
13566    3.401940
13567         NaN
13568         NaN
13569    2.636503
13570    3.033396
13571    2.721552
13572    2.636503
13573    2.976697
13574    2.778251
13575         NaN
13576    2.919999
13577         NaN
13578    2.721552
13579    3.175144
13580         NaN
13581    2.891649
13582         NaN
13583         NaN
13584    2.891649
13585         NaN
13586         NaN
13587     

`nsfg.py` also provides `ReadFemResp`, which reads the female respondents file and returns a `DataFrame`:

In [42]:
resp = nsfg.ReadFemResp()

`DataFrame` provides a method `head` that displays the first five rows:

In [43]:
resp.head()

caseid  rscrinf  rdormres  rostscrn  rscreenhisp  rscreenrace  age_a  \
0    2298        1         5         5            1          5.0     27   
1    5012        1         5         1            5          5.0     42   
2   11586        1         5         1            5          5.0     43   
3    6794        5         5         4            1          5.0     15   
4     616        1         5         4            1          5.0     20   

   age_r  cmbirth  agescrn     ...      pubassis_i      basewgt  \
0     27      902       27     ...               0  3247.916977   
1     42      718       42     ...               0  2335.279149   
2     43      708       43     ...               0  2335.279149   
3     15     1042       15     ...               0  3783.152221   
4     20      991       20     ...               0  5341.329968   

   adj_mod_basewgt     finalwgt  secu_r  sest  cmintvw  cmlstyr  screentime  \
0      5123.759559  5556.717241       2    18     1234     1222    18:26:36   
1      2846.799490  4744.191350       2    18     1233     1221    16:30:59   
2      2846.799490  4744.191350       2    18     1234     1222    18:19:09   
3      5071.464231  5923.977368       2    18     1234     1222    15:54:43   
4      6437.335772  7229.128072       2    18     1233     1221    14:19:44   

    intvlngth  
0  110.492667  
1   64.294000  
2   75.149167  
3   28.642833  
4   69.502667  

[5 rows x 3087 columns]

Select the `age_r` column from `resp` and print the value counts.  How old are the youngest and oldest respondents?

In [46]:
# Solution goes here
resp.age_r.value_counts().sort_index()

15    217
16    223
17    234
18    235
19    241
20    258
21    267
22    287
23    282
24    269
25    267
26    260
27    255
28    252
29    262
30    292
31    278
32    273
33    257
34    255
35    262
36    266
37    271
38    256
39    215
40    256
41    250
42    215
43    253
44    235
Name: age_r, dtype: int64

We can use the `caseid` to match up rows from `resp` and `preg`.  For example, we can select the row from `resp` for `caseid` 2298 like this:

In [47]:
resp[resp.caseid==2298]

caseid  rscrinf  rdormres  rostscrn  rscreenhisp  rscreenrace  age_a  \
0    2298        1         5         5            1          5.0     27   

   age_r  cmbirth  agescrn     ...      pubassis_i      basewgt  \
0     27      902       27     ...               0  3247.916977   

   adj_mod_basewgt     finalwgt  secu_r  sest  cmintvw  cmlstyr  screentime  \
0      5123.759559  5556.717241       2    18     1234     1222    18:26:36   

    intvlngth  
0  110.492667  

[1 rows x 3087 columns]

And we can get the corresponding rows from `preg` like this:

In [48]:
preg[preg.caseid==2298]

2610    18.08
2611    20.00
2612    21.41
2613    24.66
Name: agepreg, dtype: float64

How old is the respondent with `caseid` 1?

In [50]:
# Solution goes here
preg[preg.caseid==1].agepreg

0    33.16
1    39.25
Name: agepreg, dtype: float64

What are the pregnancy lengths for the respondent with `caseid` 2298?

In [58]:
# Solution goes here
preg[preg.caseid==2298].prglngth

2610    40
2611    36
2612    30
2613    40
Name: prglngth, dtype: int64

What was the birthweight of the first baby born to the respondent with `caseid` 5012?

In [59]:
# Solution goes here
p = preg[preg.caseid==5012]
p[preg.pregordr==1].birthwgt_lb

/Users/filess/homebrew/lib/python3.5/site-packages/ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until


5515    6.0
Name: birthwgt_lb, dtype: float64